name: CICD
on: [push]


jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Checkout LFS objects
        run: git lfs checkout
      - run: pip install poetry
      - run: make setup
      - run: make lint
      - run: make test
